export const SET_REPOS = 'SET_REPOS';
export const REPO_API_REQUEST_FAILURE = 'REPO_API_REQUEST_FAILURE';
export const REPO_API_RESPONSE_NOT_FOUND = 'REPO_API_RESPONSE_NOT_FOUND';
export const RESET = 'RESET';